### ISSUE TITLE
Getting "No such module 'EonilFileSystemEvents" error

### ISSUE THREAD

**Issue by mron** [eonil/FileSystemEvents#12]
Thank you for creating this project!

I am unable to link the module. Here are the steps I took:
1) created a new swift cocoa project in Xcode called "Simple Test"
2) copied "Project" directory from "FileSystemEvents-master" to the new project
3) followed the "A proper way to add a subproject to another Xcode project."
4) cleaned and built new project.

I get 1 error:
".../Simple Test/Simple Test/AppDelegate.swift:10:8: No such module 'EonilFileSystemEvents'"

Do I need to add a bridging header? Modify header and/or framework search paths?

**Comment by eonil** [comment]
Hello @mron. It's been a long time since I wrote this code so I forget every details, and I don't understand what your situation is. Can you show me your full project setting on a separated repository? Maybe I can help...

**Comment by mron** [comment]
Mr Hoon,
Thank you for your reply and thank you for writing this framework. I followed a video you posted on how to add a framework. The video showed essentially to steps. For some reason I had to to do a couple more. I have the framework working in my code now.

Thanks,
Ron

**Comment by eonil** [comment]
Ok. Problem solved!
