### ISSUE TITLE
Multiple errors running on Xcode 6 beta 4

### ISSUE THREAD

**Issue by franciscocgoncalves** [Eonil/FileSystemEvents#2]

**Comment by Eonil** [comment]
Thanks for reporting. I'll look into it ASAP. Maybe in this weekend.
I couldn't update source base for a while due to a deadline of day job.

**Comment by Eonil** [comment]
I could not reproduce the issue. On my machine, it is being built and working well with no compile error.
My Xcode is Version 6.3 beta 4 (6D554n). 
Am I missing something?

**Comment by franciscocgoncalves** [comment]
Thanks for looking at it. I tried to reproduce the issue again to show you but I couldn't. It must have been a Xcode bug or something.
