### ISSUE TITLE
Use FileSystemEvents in my project

### ISSUE THREAD

**Issue by yashwanthbabu** [Eonil/FileSystemEvents#3]
Hi Eonil, I am building a Mac Application and I have a requirement which meets your project. So how can I use your project as a library in my project ??

Please show me a way :)

**Comment by Eonil** [comment]
Hi Yashwanth. 

You can add my project as a subproject and add framework dependency to your project.
If you're not sure on how to do this, please see this video posting.

- [A proper way to add a subproject to another Xcode project](http://eonil-observatory.tumblr.com/post/117205738262/a-proper-way-to-add-a-subproject-to-another-xcode)

If you're looking for a static or dynamic library, I don't have a plan to support them. 
Thanks.
