### ISSUE TITLE
Ability to stop/close Event Stream

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [Eonil/FileSystemEvents#4]
I'd like to use this framework in a multi-document app, where each document window tracks one or more paths using an event stream.

When a window is closed, I would like to stop/close that event stream.

I'll look into it, but am very new to Mac OS X / Cocoa / Swift / Obj-C so will be an uphill struggle....

**Comment by Eonil** [comment]
You can stop monitoring by killing the monitor object. If you want to re-start monitoring, just make another monitor object. To do this, you need to remove all strong references to it to kill the object.

    var m: FileSystemEventMonitor? = FileSystemEventMonitor(...) 
    // now it started.
    m = nil 
    // now it stopped.

I updated README and example app to show how to stop monitoring. I hope this helps.

**Comment by Eonil** [comment]
Though I intended RAII semantics, I am still unsure whether it is a best design approach or not. Opinions are welcome.

**Comment by andrewdavidmackenzie** [comment]
OK. I didn't realize that would kill it. 
I guess the de-initializer takes care of that.
thanks.
